### ISSUE TITLE
Question about Jacbian matrix

### ISSUE THREAD

**Issue by xichaoqiang** [fpicetti/occamypy#1]
Hi, thanks for sharing this great package.

I have defined my forward problem. Is it nessary to give the function of Jacbian matrix for LeastSquares inversion? And how to define the function of Jacobian matrix?

**Comment by fpicetti** [comment]
Hi @xichaoqiang! Thanks for using this library.

For non linear problems, you need to define the forward modeling and the (linear) Jacobian operator.
In particular, you can derive its forward and adjoint functions directly from the nonlinear forward problem.

Check out the [VarPro](https://github.com/fpicetti/occamypy/blob/master/tutorials/Testing%20the%20VarPro.ipynb) tutorial, and let us know!

**Comment by xichaoqiang** [comment]
Thanks for your reply.

**Comment by xichaoqiang** [comment]
I may only have the forward Jacobian matrix obtained by numerical difference. Does the adjoint Jacobian matrix need to be defined?

**Comment by fpicetti** [comment]
I fear yes, as in adjoint-state methods you need the adjoint jacobian for computing the gradient `g = F'r = F'(f(m) - d)`.

If you know the formula of your nonlinear modeling `f(m)`, you can derive the analytic Jacobian and implement both forward and adjoint.

**Comment by xichaoqiang** [comment]
Thanks. I want to slove a simple 1-D surface wave dispersion inversion with LeastSquares algorithms.

Usually I use L-M algorithm by defing the forward and jacobian functions.

I want use occamypy to the inversion problem, because I want to constrain the inversion problem with lower/upper bounds and the reference model.

How can I do by just defing the forward and jacobian functions?

**Comment by biondiettore** [comment]
Hi @xichaoqiang,

Thanks for using the library. Try to have a look at the tutorial on the Rosenbrock benchmark ([Rosebrock](https://github.com/fpicetti/occamypy/blob/master/tutorials/Rosenbrock.ipynb)). Specifically, look at the second code block in which the Rosenbrock problem is defined. If you have to implement your own problem, you can simply inherit from occamypy.Problem and implement the constructor (__init__), objf, resf, and gradf. The last three corresponds to your objective function, and residual and gradient vector computations, respectively.

On the other hand, if you want to solve an L2-norm non-linear problem, define an occamypy.NonlinearOperator by using your forward and Jacobian operators. You have to wrap your functions within an occamypy.Operator. As @fpicetti mentioned, look at the second block of the [VarPro](https://github.com/fpicetti/occamypy/blob/master/tutorials/Testing%20the%20VarPro.ipynb) tutorial. In the following code blocks, you can see how they are used to solve a non-linear L2 problem. FYI, you are not required to define the forward part of the Jacobian operator but only the adjoint. For the bounds, you can simply pass two model vectors to occamypy.NonlinearLeastSquares as minBound and maxBound, which define the lower and upper bounds, respectively.

I hope this helps you understand how to use the library a little bit more. Let us know if you have other difficulties with it.
Cheers!
