### ISSUE TITLE
Is the 2D Travel-time tomography tutorial suit for cross-hole tomography?

### ISSUE THREAD

**Issue by xichaoqiang** [fpicetti/occamypy#20]
Hello Dr. @biondiettore 

Thanks for sharing this package. This package is very interesting.

And the 2D travel-time tomography tutorial is very attractive.

Is the 2D travel-time tomography suit for cross-hole type tomography?

Best regards,
Xi

**Comment by biondiettore** [comment]
Hi Xi,

The 2D travel-time tomography example can be definitely used for cross-well/cross-hole tomography. It should be fairly simple to change that tutorial to your purpose.

Best,

Ettore

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
