### ISSUE TITLE
A quetsion about adjoint state of eikonal equation.

### ISSUE THREAD

**Issue by xichaoqiang** [fpicetti/occamypy#34]
@fpicetti @biondiettore 

Dear sir,

Thanks for this great package.

Your tutorial helps me alot.

However, I want invert some value based eikonal equation and it's adjoint state equation.

My goal is to fit Bessel_j0(a*t), where a is a constant, t is travel time.

How to invert it using adjoint state? This problem has plagued me for several months.

Looking forward to your reply.

Best regards,
Xi

**Comment by xichaoqiang** [comment]
My opinion is new gradient of bessel function with chain rule. I'm not sure is this right.
## $b =J_0(a*t)$

##  $\nabla b= \partial b /\partial t *\nabla t$

## $\nabla b=\sum\limits_{k=1}^{n} \nabla t_i  * a*(- J_1(a*t_i))$

**Comment by biondiettore** [comment]
Hi Xi,

What I would do is to create two non-linear operator objects. One for the Eikonal equation (see tutorial https://github.com/fpicetti/occamypy/blob/master/tutorials/2D%20Travel-time%20tomography%20using%20the%20Eikonal%20equation.ipynb), and one for the Bessel function applied to the scaled traveltimes. Then use the CombNonlinearOp to obtain what you need (line 148 https://github.com/fpicetti/occamypy/blob/master/occamypy/operator/nonlinear.py), this will also correctly apply the chain rule you mention. 

Hope this helps!

**Comment by xichaoqiang** [comment]
@biondiettore Thanks for your kindly reply.I’ll try it.
